### ISSUE TITLE
Can't create a model in scene

### ISSUE THREAD

**Issue by kolyan3445** [KiwifruitDev/SFM-Asset-Browser#2]
![image](https://user-images.githubusercontent.com/55030059/213431110-b6d6994c-5b58-47f5-8f56-986cc20b883a.png)

**Comment by KiwifruitDev** [comment]
Thank you for reporting this issue.

I'm currently investigating it, seems to be related to the tagging system.

Hopefully this is solved soon.

**Comment by KiwifruitDev** [comment]
Issue seems to be caused by unicode strings within Python itself.

Fixing as of now.
