### ISSUE TITLE
"No JSON object could be decoded" when loading assetTags.json

### ISSUE THREAD

**Issue by Jeroitsme** [KiwifruitDev/SFM-Asset-Browser#3]
when i try to press on the script, scripts, kiwifruitdev, assest browswer, a window pops up which says the following in the photo:
![image](https://user-images.githubusercontent.com/92041067/214937090-f9338068-21ce-4ba0-a221-4fe46ff11609.png)

**Comment by KiwifruitDev** [comment]
Hi, can you try to save this to a file called `assetTags.json` and place it into your `assetbrowser` folder in SFM?

https://gist.githubusercontent.com/KiwifruitDev/2bf27f66b3ea717ee754f7fe73eaaab6/raw/3287f3112bf6a854720534d0a8b33da5f9e090a0/assetTags.json

Let me know if this works.

**Comment by Jeroitsme** [comment]
Yes! It works, ty sm
